services:
  postgres:
    image: postgres:15
    container_name: blog-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: blogdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d
    networks:
      - soa-network

  blog-service:
    build: .
    container_name: blog-service
    depends_on:
      - postgres
    environment:
      - DB_HOST=postgres
      - DB_USER=postgres
      - DB_PASSWORD=password
      - DB_NAME=blogdb
      - DB_PORT=5432
    networks:
      - soa-network

volumes:
  postgres_data:

networks:
  soa-network:
    external: true